### ISSUE TITLE
Enable File Attachments not working with sprout forms

### ISSUE THREAD

**Issue by aswinsatish** [barrelstrength/craft-sprout-forms#129]
### Description
I am using CRAFTCMS:  Craft CMS 2.6.3019 and Sprout Forms 2.5.2

When i enable the  "Enable File Attachments" in the settings of form the notification is not being sent and when it is disabled the email notifications are received .

### Steps to reproduce

1.
2.

### Additional info

- Craft version:
- PHP version:
- Database driver & version:
- Plugins & versions:

### Notify

- [ ] [Support conversation](https://app.frontapp.com/open/cnv_15ebt77)

**Comment by BenParizek** [comment]
@aswinsatish Can you try updating to the latest Sprout Forms v2.5.3 and let me know if that resolves the issue:
https://github.com/barrelstrength/craft-sprout-forms/releases/tag/v2.5.3

We just fixed a couple file attachment related bugs in that release yesterday.

**Comment by aswinsatish** [comment]
@BenParizek I tried updating to this release, still facing the same issue, when attachments are enabled  the notification email is not being sent and when they are turned of the notification emails are received.
Amazon SES is being used for smtp

**Comment by BenParizek** [comment]
Thanks for the additional details @aswinsatish. We'll look into it.

**Comment by andrelopez** [comment]
Hi @aswinsatish We're still unable to recreate this issue. We may need more info to help out. Could you please recreate this issue send us an email to sprout@barrelstrengthdesign.com with a zip file of your logs located in craft/storage/runtime/logs

Best,

**Comment by aswinsatish** [comment]
Facing the same issue while enabling   "Enable File Attachments" in the settings of form the notification is not being sent. Though it is shown in the Sprout email section. Can you be specific which log file you require  . Will sending sproutforms.log help?

**Comment by BenParizek** [comment]
@aswinsatish The more logs you can send the better. We're trying to get an understanding of what's happening and we're unable to recreate it right now. sproutforms.log and sproutemail.log would be good ones. So would craft.log. While they may not be necessary the phperrors.log or any other plugin log files that could be related to the issue could also reveal something.

If you are able to share your database (or even just the specific tables that relate to Sprout Forms and Sprout Email) or the templates related to the email you are sending, those may be other things we need at some point to help troubleshoot.

**Comment by aswinsatish** [comment]
@BenParizek 
Sorry for the delayed response. When attachments is enabled in sprouftforms we get this error in craftlog.
******************************************************************************************************
2018/12/12 05:44:27 [error] [application] Could not delete the file /var/www/html/craftv/craft/storage/runtime/assets/sources/331268.pdf because the file does not exist.
2018/12/12 05:44:27 [error] [application] Email error: Could not access file: /var/www/html/craftv/craft/storage/runtime/assets/tempuploads/user_1/field_264/tuning.pdf
******************************************************************************************************

I have tried the asset sources from s3 as well as local folder. 
Hope this log will give some insights.

**Comment by BenParizek** [comment]
Brad from P&T shares the following thoughts:

> Craft 2 uses PhpMailer to send emails (https://github.com/PHPMailer/PHPMailer) and that "Could not access file" message is coming from PhpMailer: https://github.com/PHPMailer/PHPMailer/blob/70362997bda4376378be7d92d81e2200550923f7/class.phpmailer.php#L1767 which is thrown here: https://github.com/PHPMailer/PHPMailer/blob/70362997bda4376378be7d92d81e2200550923f7/class.phpmailer.php#L2513-L2515

> You can see all it's doing is calling PHP's is_file method to see if the file exists and if not, throw the error.

> That method will return false if (obviously) the file doesn't exist, but also if PHP doesn't have permissions to read it or any parent directories of the file that's being checked don't have the execute bit set.

Have you [set permissions](https://docs.craftcms.com/v2/installing.html#pre-flight-check) to the storage folder correctly and recusively? Make sure the user:group that owns the folder and the user:group your web server is configured to run PHP as are set to work with one another.

Can you confirm the /var/www/html/craftv1/craft/storage/runtime/assets/tempuploads/user_1/field_264/tuning.pdf actually exist on the server?

**Comment by BenParizek** [comment]
The issue here turned out to be that the Asset Field on the Form was using an incorrect Upload Location sub-folder value which was likely causing Craft to misunderstand where the actual file could be found. Removing the incorrect Upload Location subfolder value got things working.
