### ISSUE TITLE
Improve error messaging when no Notification Event is selected

### ISSUE THREAD

**Issue by jaydensmith** [barrelstrength/craft-sprout-forms#283]
### Description
I cannot create new notifications using Sprout Forms (3.0.0-beta.57). The exception from the logs:

```
2019-06-05 15:43:16 [-][1][-][error][Error] Error: Call to a member function getSettingsHtml() on null in /home/forge/[redacted]/vendor/barrelstrength/sprout-base-email/src/controllers/NotificationsController.php:292
Stack trace:
#0 [internal function]: barrelstrength\sproutbaseemail\controllers\NotificationsController->actionSaveNotificationEmail()
#1 /home/forge/[redacted]/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#2 /home/forge/[redacted]/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#3 /home/forge/[redacted]/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('save-notificati...', Array)
#4 /home/forge/[redacted]/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save-notificati...', Array)
#5 /home/forge/[redacted]/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('sprout-base-ema...', Array)
#6 /home/forge/[redacted]/vendor/craftcms/cms/src/web/Application.php(565): craft\web\Application->runAction('sprout-base-ema...', Array)
#7 /home/forge/[redacted]/vendor/craftcms/cms/src/web/Application.php(281): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#8 /home/forge/[redacted]/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#9 /home/forge/[redacted]/public_html/index.php(36): yii\base\Application->run()
#10 {main}
```

### Steps to reproduce

1. Create new notification
2. Press save

### Additional info

- Craft version: 3.1.29
- PHP version: 7.1.28
- Database driver & version: mysql  Ver 15.1 Distrib 10.3.11-MariaDB
- Plugins & versions: Sprout Forms 3.0.0-beta.57

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_kvsz)

**Comment by BenParizek** [comment]
@jaydensmith I'm going to add this to the list to improve the workflow and error messaging here but I believe the issue is easily solvable.

That error means that you have not selected an Event for the Notification. In the right sidebar, find the Events section and select "When a form entry is saved (Sprout Forms)". Configure that event however you'd like and resave and things should work.

**Comment by jaydensmith** [comment]
Hey @BenParizek,

I have confirmed that there is definitely a form and event selected. I recreated the notification and now receive a different error:

```
2019-06-06 13:47:52 [-][-][-][error][barrelstrength\sproutbaseemail\services\NotificationEmailEvents::handleDynamicEvent] When a form entry is saved (Sprout Forms) event does not validate: {"whenNew":["When New cannot be blank."],"whenUpdated":["When Updated cannot be blank."],"event":["The Form associated with the saved Form Entry Element does not match any selected Forms."]}
```

This seems strange to me, the notification is configured correctly.

**Comment by BenParizek** [comment]
@jaydensmith Sounds like something is up. I'm unable to recreate this after I configure an Event.

Would you be able to send over your db or at least the sproutforms tables in your db to sprout@barrelstrengthdesign.com so we can take a closer look?

**Comment by BenParizek** [comment]
@jaydensmith I believe latest Sprout Forms (v3.0.0) release should resolve this issue, but let me know if you still run into anything. I've been able to create and send a test email with the database you sent over but I'm not 100% sure I'm recreating your specific use case.

**Comment by jaydensmith** [comment]
Hey @BenParizek, I'm afraid this did not fix the issue. It seems only 1 form will send emails.
I had a dig around and found this:

```php
/**
 * This method hands things off to Sprout Email when a Notification Event we registered gets triggered.
 *
 * @param                       $notificationEmailEventClassName
 * @param Event                 $event
 * @param NotificationEvent     $eventHandlerClass
 *
 * @return bool
 * @throws \Throwable
 */
public function handleDynamicEvent($notificationEmailEventClassName, Event $event, NotificationEvent $eventHandlerClass): bool
{
    Craft::info(Craft::t('sprout-base-email', 'A Notification Event has been triggered: {eventName}', [
        'eventName' => $eventHandlerClass->getName()
    ]));

    // Get all Notification Emails that match this Notification Event
    $notificationEmails = SproutBaseEmail::$app->notifications->getAllNotificationEmails($notificationEmailEventClassName);

    if ($notificationEmails) {

        /** @var NotificationEmail $notificationEmail */
        foreach ($notificationEmails as $notificationEmail) {

            // Add the Notification Event settings to the $eventHandlerClass
            $settings = Json::decode($notificationEmail->settings);

            /** @var NotificationEvent $eventHandlerClass */
            $eventHandlerClass = new $eventHandlerClass($settings);

            $eventHandlerClass->notificationEmail = $notificationEmail;
            $eventHandlerClass->event = $event;

            if (!$eventHandlerClass->validate()) {
                Craft::error($eventHandlerClass->getName().' event does not validate: '.json_encode($eventHandlerClass->getErrors()), __METHOD__);
                return false;
            }

            $object = $eventHandlerClass->getEventObject();
            $notificationEmail->setEventObject($object);

            // Don't send emails for disabled notification email entries.
            if (!$notificationEmail->isReady()) {
                continue;
            }

            SproutBaseEmail::$app->notifications->sendNotificationViaMailer($notificationEmail);

            $sendNotificationEmailEvent = new SendNotificationEmailEvent([
                'event' => $event,
                'notificationEmail' => $notificationEmail,
            ]);

            $this->trigger(self::EVENT_SEND_NOTIFICATION_EMAIL, $sendNotificationEmailEvent);

        }
    }

    return true;
}
```

Can you elaborate on the point of this function, namely this part:
```php
if (!$eventHandlerClass->validate()) {
    Craft::error($eventHandlerClass->getName().' event does not validate: '.json_encode($eventHandlerClass->getErrors()), __METHOD__);
    return false;
}
```

It seems to me that only the first notification in the array is being tested then just returning false? It works for me once I change this to `continue`.

**Comment by BenParizek** [comment]
Thanks @jaydensmith. That points me the right direction. I've was able to recreate the issue and solve it with your suggestion. Fixing this should solve two bug scenarios:

1. Notification Events that come after other Notification Event rules that don't match the current Notification Event will now send
2. Forms with Multiple Notifications will now send both Notifications

This is fixed in the latest release: v3.0.1

**Comment by krizzzly** [comment]
@BenParizek we experience the same error in the logs, we receive multiple equal warnings for 1 form submission.
i can confirm that the form that is submitted has a notification on entry creation attached, and also the email is sent out correctly.

```
2022-04-04 11:26:45 [-][1][-][error][barrelstrength\sproutbaseemail\services\NotificationEmailEvents::handleDynamicEvent] When a form entry is saved (Sprout Forms) event does not validate: {"event":["The Form associated with the saved Form Entry Element does not match any selected Forms."]}
```

thx for support
