### ISSUE TITLE
User group receives Unauthorized message when adding/editing Notification

### ISSUE THREAD

**Issue by jrrdnx** [barrelstrength/craft-sprout-forms#477]
### Description

We have a Client Administrator group that currently has access to both "View Notifications" and "Edit Notification Emails" permission settings.

When attempting to add/edit a new Notification, they are directed to a "Unauthorized: User is not permitted to perform this action" screen and are unable to save.

### Steps to reproduce

1. Create a new Notification, adding all relevant details
2. Click Save

### Additional info

 * Craft version: Craft Pro 3.4.18
 * PHP version: 7.4.2
 * Database driver & version: MySQL 5.7.28
 * Plugins & versions: 3.11.3

**Comment by BenParizek** [comment]
Thanks for reporting @jrrdnx. This has been addressed in v3.11.4

**Comment by jrrdnx** [comment]
@BenParizek Thanks for the help Ben. Unfortunately the client is still having issues creating new notifications.

Here is their description of what's happening:

> Sorry, I just tried out the Notifications again this morning and it is giving me an "Internal Server Error" message when I try to create a new notification. When I go back the new notification is showing up, but when I click to edit it I receive the error message again. It is allowing me to open the two existing notifications without an error message.

Related error log:

```
2020-05-18 10:20:33 [-][28501][e99cnfh18mg0vbk000jgn58716][error][yii\web\HttpException:403] yii\web\ForbiddenHttpException: User is not permitted to perform this action. in /home/domaincom/domain.com/vendor/craftcms/cms/src/web/Controller.php:285
Stack trace:
#0 /home/domaincom/domain.com/vendor/barrelstrength/sprout-base-email/src/controllers/NotificationsController.php(115): craft\web\Controller->requireAdmin()
#1 [internal function]: barrelstrength\sproutbaseemail\controllers\NotificationsController->actionEditNotificationEmailSettingsTemplate()
#2 /home/domaincom/domain.com/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#3 /home/domaincom/domain.com/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams()
#4 /home/domaincom/domain.com/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction()
#5 /home/domaincom/domain.com/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction()
#6 /home/domaincom/domain.com/vendor/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction()
#7 /home/domaincom/domain.com/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction()
#8 /home/domaincom/domain.com/vendor/craftcms/cms/src/web/Application.php(276): yii\web\Application->handleRequest()
#9 /home/domaincom/domain.com/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest()
#10 /home/domaincom/domain.com/web/index.php(24): yii\base\Application->run()
#11 {main}
2020-05-18 10:20:33 [-][28501][e99cnfh18mg0vbk000jgn58716][info][application] $_GET = []
```

**Comment by jrrdnx** [comment]
@BenParizek I updated to 3.11.7 this morning after seeing #479 and the client isn't having any issues with notifications, only the following:

> I am still receiving the "Unauthorized. User is not permitted to perform this action" message when I try to view each entry.

The "View Form Entries" permission is selected, but not the "Edit Form Entries" permission. Since this is related to a different permission, do you want me to open a new issue for this?

**Comment by BenParizek** [comment]
@jrrdnx We can keep this a part of this thread. I haven't had time to dig into this yet but should have some time soon to try to recreate.

**Comment by rbrv** [comment]
Having the same problem here...

**Comment by BenParizek** [comment]
@jrrdnx @rbrv The 'View Form Entries' permission should be resolved in v3.12.0. A user with View Form Entries permission can now see the Edit page but the fields will only display as `readonly` and there will be no option to update the page unless they have the Edit Form Entries permission.
