### ISSUE TITLE
File Upload not working - no error

### ISSUE THREAD

**Issue by cstoerzer** [barrelstrength/craft-sprout-forms#580]
### Description

I set up a new form and use a file upload field - everything gets displayed correctly and I don't get any errors. Entries are not strored in the DB - just notification. Mail is sent, but the field is missing completely. Asset is also not stored in selected volume. So it seems that it is just ignored.

### Additional info

Reload Page

- Craft version:Craft Pro 3.6.17
- PHP version: 7.4.20
- Database driver & version: MySQL 5.7.34
- Plugins & versions: Sprout Forms | 3.13.5 / Sprout redirects 1.5.3

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3r7d9)

**Comment by cstoerzer** [comment]
Hi,

I tried the same now, with a clean install of craft cms and sprout forms. Same behavior – E-Mail is sent, but no file attachment to email and no file upload to volume.

Any suggestions?

Christian

**Comment by BenParizek** [comment]
@cstoerzer This issue had to do with a change in the Element publishing workflow introduced in Craft 3.7.

I've just released Sprout Forms 3.13.7 which should resolve the issue. You will be required to upgrade to at least Craft 3.7.5 for the fix.

**Comment by cstoerzer** [comment]
@BenParizek thank you - works now if saving of entries is enabled.

But does still not work, if saving of form entries is disabled. But I can live with that for now.
